# Generated by Django 3.2.9 on 2021-12-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_prodjects_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodjects',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='works',
            old_name='Name',
            new_name='name',
        ),
    ]
