# Generated by Django 3.2.9 on 2021-12-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211211_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='color',
            field=models.TextField(null=True),
        ),
    ]
