# Generated by Django 3.2.9 on 2021-12-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_works_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodjects',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
