# Generated by Django 3.2.9 on 2021-12-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_prodjects_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodjects',
            name='text',
        ),
    ]
