# Generated by Django 3.2.9 on 2022-02-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220224_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodjects',
            options={'verbose_name': 'Проект'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': 'Умение'},
        ),
        migrations.AlterField(
            model_name='works',
            name='color',
            field=models.TextField(null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='works',
            name='descriptionEN',
            field=models.TextField(null=True, verbose_name='Описание(Английский)'),
        ),
        migrations.AlterField(
            model_name='works',
            name='descriptionRU',
            field=models.TextField(null=True, verbose_name='Описание(Русский)'),
        ),
        migrations.AlterField(
            model_name='works',
            name='name',
            field=models.TextField(verbose_name='Име'),
        ),
    ]
